In [1]:
using LinearAlgebra

# Matrizes em $\mathbb{R}^{m\times n}$
###  Matrizes
**Criando uma matriz apartir das entradas:** Em Julia, as matrices são representadas como um arrays de dimensão $2$. São construidas dando os elementos em cada linha, separados por um espaço, e as linhas são separadas por ';'. 

Exemplo: Dada a matriz
$$
A = \begin{bmatrix}
 1.2 & -1 & 12.7 & 1\\
 2.5 & -1.1 & -6.1 & 9\\
 0 & 2.0 & 0 & -7.1
\end{bmatrix} \in \mathbb{R}^{3 \times 4}
$$
é definido por:

In [2]:
A = [1.2 -1 12.7 1;
     2.5 -1.1 -6.1 9;
     0 2.0 0 -7.1]

3×4 Matrix{Float64}:
 1.2  -1.0  12.7   1.0
 2.5  -1.1  -6.1   9.0
 0.0   2.0   0.0  -7.1

In [3]:
A= [0.0 1 2 3; 2 3 4 5]

2×4 Matrix{Float64}:
 0.0  1.0  2.0  3.0
 2.0  3.0  4.0  5.0

In [86]:
A = [1.2 -1 12.7 1; 2.5 -1.1  -6.1 9; 0 2.0 0 -7.1]

3×4 Matrix{Float64}:
 1.2  -1.0  12.7   1.0
 2.5  -1.1  -6.1   9.0
 0.0   2.0   0.0  -7.1

In [87]:
m, n = size(A)  # A função size(A) da o tamanho como uma tupla
n

4

In [88]:
m

3

In [89]:
size(A,1)   # A função size(A,1) da somente o número de linhas

3

In [8]:
size(A,2)   # A função size(A,2) da somente o número de colunas

4

In [90]:
# Criamos uma função que verifica se 
# a matriz é "alta" retornando um dado Booleano

alta(X) = size(X,1) > size(X,2);
alta(A)

false

**Indices da Matriz:** Usamos `A[i,j]` para referenciar a entrada $a_{ij}$ da matriz `A`. 

In [91]:
A

3×4 Matrix{Float64}:
 1.2  -1.0  12.7   1.0
 2.5  -1.1  -6.1   9.0
 0.0   2.0   0.0  -7.1

In [92]:
A[2,3] # Obtemos a entrada a₂₃ da matriz A

-6.1

In [93]:
A[3,4] = 10000.5; # Definimos a entrada a₃₄ de A para 10000.5
A

3×4 Matrix{Float64}:
 1.2  -1.0  12.7      1.0
 2.5  -1.1  -6.1      9.0
 0.0   2.0   0.0  10000.5

**Indexação de índice único** Julia permite que acesse uma entrada de uma matriz usando apenas um índice. 
Para isso, precisamos saber que as matrizes em Julia são armazenadas na ordem da coluna principal. 
Isso significa que uma matriz pode ser considerada como um array de dimensão 1, com a $1^{\circ}$ coluna empilhada em cima da $2^{\circ}$, empilhada em cima da $3^{\circ}$ e assim por diante. Por exemplo:

$$
B =
\begin{bmatrix}
3 & -1 & 20\\
1000 & -52 & -23.4
\end{bmatrix}
$$
são armazenadas na ordem
$$3, −1, 20, 1000, -52, -23.4$$
Desta forma com um indice, `B[6]` é o $6^{\circ}$ elemento desta sequencia.

In [94]:
B = [ 3 -1 20; 1000 -52 -23.4]
B[3]

-1.0

**Igualdade de matrices:** 

In [95]:
B = copy(A);
B[2,2] = 0;

A == B    # determina se as matrizes A e B são iguais

false

In [96]:
A .== B    
# Cria uma matriz com entradas Booleanas, 
# dependendo se as entradas correspondentes A e B são iguais

3×4 BitMatrix:
 1  1  1  1
 1  0  1  1
 1  1  1  1

In [97]:
sum(A .== B) # fornece o numero de entradas de A e B que são iguais

11

## Vetores linha e coluna

In [98]:
a = [ 3.1 1.5 0.9 -22] # Um vetor linha ou uma matriz 1x4

1×4 Matrix{Float64}:
 3.1  1.5  0.9  -22.0

In [99]:
b = [ 0.9; 22.6; 11; 0.9] # Um vetor coluna ou uma matriz 4x1

4-element Vector{Float64}:
  0.9
 22.6
 11.0
  0.9

### Submatrizes 

In [100]:
A = [ 0 1 2 3 -10; 4 5 6 7 -20 ; 8 9 10 11 -30; -1 -2 -3 -4 -40]

4×5 Matrix{Int64}:
  0   1   2   3  -10
  4   5   6   7  -20
  8   9  10  11  -30
 -1  -2  -3  -4  -40

In [101]:
A[1:3,3:4]  # Usando a notação de dois pontos podemos extrair uma submatriz

3×2 Matrix{Int64}:
  2   3
  6   7
 10  11

In [102]:
A[:,4]  # 4° coluna de A

4-element Vector{Int64}:
  3
  7
 11
 -4

In [103]:
A[3,:] # 3° linha de A, tem como saida um vetor coluna!

5-element Vector{Int64}:
   8
   9
  10
  11
 -30

In [104]:
# Podemos inverter a ordem das linhas de uma matriz
X = copy(A)  
m = size(X,1)
X[m:-1:1,:] # Matriz X com linhas na ordem reversa

4×5 Matrix{Int64}:
 -1  -2  -3  -4  -40
  8   9  10  11  -30
  4   5   6   7  -20
  0   1   2   3  -10

In [105]:
B = [ 1 -3 ; 2 0 ; 1 -2]

3×2 Matrix{Int64}:
 1  -3
 2   0
 1  -2

In [106]:
B[:]   
#  B[:] é um vetor de tamanho 3*2 que consiste 
#      nas colunas de B empilhadas umas sobre as outras 

6-element Vector{Int64}:
  1
  2
  1
 -3
  0
 -2

In [107]:
# reshape(B,(k,l)) cria uma nova matriz kxl,
# com as entradas obtidas na ordem da coluna principal de B.
# (Para isto mn = kl)

reshape(B,(2,3)) 

2×3 Matrix{Int64}:
 1   1   0
 2  -3  -2

In [108]:
reshape(B,(6,1))

6×1 Matrix{Int64}:
  1
  2
  1
 -3
  0
 -2

## Matrizes em Bloco 

In [109]:
B = [ 1 2 3 ];        # Matriz 1x3

C = [ 23 ];           # Matriz 1x1

D = [ -1 -2 100 ; 10 20 30]; # Matriz 2x3

E = [-1 ; 1 ];         # Matriz 2x1

# Construindo uma matriz por blocos 3x4

A = [B C ; 
    D E]

3×4 Matrix{Int64}:
  1   2    3  23
 -1  -2  100  -1
 10  20   30   1

**Interpretação de colunas e linhas de uma matriz** A matriz $A\in \mathbb{R}^{m\times n}$ pode ser interpretada como uma coleção de $n$ vetores em $\mathbb{R}^m$ (as colunas) ou uma coleção de $m$ vetores linha (as linhas).

- Julia distingue entre uma matriz (uma matriz bidimensional) e uma matriz de vetores.
- Uma matriz (ou uma tupla) de vetores de coluna pode ser convertida em uma matriz usando a função de concatenação horizontal `hcat`.

In [110]:
a = [ [10.1, 20.2], [34.1, 35.2], [41.2, 28.5] ] 
# array de vectores de dimensão 2

3-element Vector{Vector{Float64}}:
 [10.1, 20.2]
 [34.1, 35.2]
 [41.2, 28.5]

In [112]:
A = hcat(a...) 

# O operador ... em hcat(a...) divide o array a em seus elementos, 
# é o mesmo que hcat(a[1],a[2],a[3])

2×3 Matrix{Float64}:
 10.1  34.1  41.2
 20.2  35.2  28.5

In [113]:
a = [ [1. 2.], [4. 5.], [7. 8.] ] # array de matrices 1x2

3-element Vector{Matrix{Float64}}:
 [1.0 2.0]
 [4.0 5.0]
 [7.0 8.0]

In [114]:
A = vcat(a...)  #vcat concatena um array de arrays verticalmente

3×2 Matrix{Float64}:
 1.0  2.0
 4.0  5.0
 7.0  8.0

## Matrizes Zero e Identidade
### Zero matrices

In [115]:
zeros(4,3)  # Cria uma matriz zero de tamanho 3×2

4×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

### Matrizes Identidade 

In [116]:
Iden(n) = 1.0*Matrix(I,n,n)  # Matriz identidade de ordem n
Iden(5)

5×5 Matrix{Float64}:
 1.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  1.0

In [117]:
A = [ 15 10 2; 0 3 -1]

2×3 Matrix{Int64}:
 15  10   2
  0   3  -1

In [118]:
[A I]

2×5 Matrix{Int64}:
 15  10   2  1  0
  0   3  -1  0  1

In [119]:
[A ; I]

5×3 Matrix{Int64}:
 15  10   2
  0   3  -1
  1   0   0
  0   1   0
  0   0   1

In [120]:
B = [ 10 20 ; 30 40 ]

2×2 Matrix{Int64}:
 10  20
 30  40

In [121]:
B + Iden(2) == B + I

true

In [122]:
ones(2,3) # Cria uma matriz de 1's de tamanho 2 x 3

2×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0

**Matrizes Diagonais** 

In [124]:
diagm([10, 2, 3])  # cria uma matriz diagonal apartir do vetor [1, 2, 3]

3×3 Matrix{Int64}:
 10  0  0
  0  2  0
  0  0  3

In [125]:
 diagonal(x) = diagm(0 => x)  # Cria uma matriz diagonal apartir do vetor x

diagonal (generic function with 1 method)

In [126]:
diagonal([1,2,3])

3×3 Matrix{Int64}:
 1  0  0
 0  2  0
 0  0  3

In [127]:
C = [10 11 12 13; 21 22 23 24; 1 1 1 1]

3×4 Matrix{Int64}:
 10  11  12  13
 21  22  23  24
  1   1   1   1

In [128]:
diag(C) # Pega as entradas da diagonal da matriz C, e as coloca em um vetor

3-element Vector{Int64}:
 10
 22
  1

**Matrizes Randomicas**

In [129]:
rand(4,3) # Cria uma matriz 4x3 com entradas randomicas entre 0 e 1 

4×3 Matrix{Float64}:
 0.573696  0.629894  0.997389
 0.638515  0.191852  0.475293
 0.541116  0.5932    0.545763
 0.152903  0.595003  0.871562

In [130]:
randn(3,4) 
# Cria uma matriz 3 x 4 com entradas randomicas com distribuição normal 

3×4 Matrix{Float64}:
 -0.0267572  -2.15656   -0.244261  -0.104523
  0.650742   -0.180642  -1.14439   -0.259575
  0.283766    1.424     -0.606046  -0.682011

### Matrizes esparsas

$$
  A = 
  \begin{bmatrix} 
  −2.1 &  0.00 &  72.19 &  0.00 &  0.00 \\
  -0.15  & 9.3 &  0.00 &  0.00 &  0.00 \\
  0.00  & 0.00  & 1.30 &  0.00 &  0.00 \\
  0.00  & 0.00  & 0.00  & -5.13  & 0.00 
  \end{bmatrix}.
$$

In [48]:
using SparseArrays

In [131]:
M = [ 1, 2, 2, 1, 3, 4 ] # indices das linhas não zeros
N = [ 1, 1, 2, 3, 3, 4 ] # indices das colunas
V = [ -2.1, -0.15, 9.3, 72.19, 1.30, -5.13 ] # valores
A = sparse(M, N, V, 4, 5)

4×5 SparseMatrixCSC{Float64, Int64} with 6 stored entries:
 -2.1    ⋅   72.19    ⋅     ⋅ 
 -0.15  9.3    ⋅      ⋅     ⋅ 
   ⋅     ⋅    1.3     ⋅     ⋅ 
   ⋅     ⋅     ⋅    -5.13   ⋅ 

In [132]:
nnz(A)

6

In [51]:
A = sparse([1, 3, 2, 1], [1, 1, 2, 3],
    [1.0, 2.0, 3.0, 4.0], 3, 3)

3×3 SparseMatrixCSC{Float64, Int64} with 4 stored entries:
 1.0   ⋅   4.0
  ⋅   3.0   ⋅ 
 2.0   ⋅    ⋅ 

In [52]:
B = Array(A) 
# A função Array converte a matriz esparsa A em matrizes regulares

3×3 Matrix{Float64}:
 1.0  0.0  4.0
 0.0  3.0  0.0
 2.0  0.0  0.0

In [53]:
B[1,3] = 0.0;
sparse(B) # fornece a matriz esparsa equivalente.

3×3 SparseMatrixCSC{Float64, Int64} with 3 stored entries:
 1.0   ⋅    ⋅ 
  ⋅   3.0   ⋅ 
 2.0   ⋅    ⋅ 

In [54]:
spzeros(4,5)    # Cria uma matriz zero esparsa 4x5

4×5 SparseMatrixCSC{Float64, Int64} with 0 stored entries:
  ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅ 

In [55]:
sparse(1.0I,4,4) # Cria uma matriz identidade esparsa de ordem 4

4×4 SparseMatrixCSC{Float64, Int64} with 4 stored entries:
 1.0   ⋅    ⋅    ⋅ 
  ⋅   1.0   ⋅    ⋅ 
  ⋅    ⋅   1.0   ⋅ 
  ⋅    ⋅    ⋅   1.0

In [56]:
# função para criar uma matriz identidade esparsa de ordem n
Ide_esparsa(n) = sparse(1.0I,n,n) 

Ide_esparsa (generic function with 1 method)

In [57]:
Ide_esparsa(4)

4×4 SparseMatrixCSC{Float64, Int64} with 4 stored entries:
 1.0   ⋅    ⋅    ⋅ 
  ⋅   1.0   ⋅    ⋅ 
  ⋅    ⋅   1.0   ⋅ 
  ⋅    ⋅    ⋅   1.0

In [58]:
a =[1, 2, 3, 4, 5, 8];
diagonalesparsa(x)= sparse(1.0I,length(x),length(x))
diagonalesparsa(a)

6×6 SparseMatrixCSC{Float64, Int64} with 6 stored entries:
 1.0   ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅   1.0   ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅   1.0   ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅   1.0   ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅   1.0   ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅   1.0

In [59]:
# sprand(m,n,d) cria uma matriz esparsa aleatória m x n, 
# onde d é a densidade das entradas não nulas (com entradas entre 0 e 1) 

A = sprand(10000,10000,10^-7)  
# cria uma matriz aleatoria esparsa 10000×10000, com uma densidade 10^{-7}

10000×10000 SparseMatrixCSC{Float64, Int64} with 8 stored entries:
⎡⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎤
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠠⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠁⠀⠀⠀⠀⠀⠀⠀⠂⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠐⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎣⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎦

### Transposta, soma e norma 
**Transposta**

In [133]:
A = [1 2 3 4; -2 -4 -6 -8]

2×4 Matrix{Int64}:
  1   2   3   4
 -2  -4  -6  -8

In [134]:
A'   # Matriz transposta

4×2 adjoint(::Matrix{Int64}) with eltype Int64:
 1  -2
 2  -4
 3  -6
 4  -8

**Soma, subtração e multiplicação por um escalar**

In [135]:
A = [ 0 4; 7 0; 3 1]

3×2 Matrix{Int64}:
 0  4
 7  0
 3  1

In [136]:
B = [ 1 2; 2 3; 0 4]

3×2 Matrix{Int64}:
 1  2
 2  3
 0  4

In [137]:
A + B

3×2 Matrix{Int64}:
 1  6
 9  3
 3  5

In [138]:
5.8 * A   # podemos multiplicar A*5.8

3×2 Matrix{Float64}:
  0.0  23.2
 40.6   0.0
 17.4   5.8

**Operações elemento-elemento**

In [139]:
C = A .* B    # multiplicação elemento-elemento cᵢⱼ= aᵢⱼ * bᵢⱼ 

3×2 Matrix{Int64}:
  0  8
 14  0
  0  4

In [140]:
X =[ 1 2; 3 0]
Y = exp.(X) # cria uma matriz Y, com elementos yᵢⱼ = exp(xᵢⱼ)

2×2 Matrix{Float64}:
  2.71828  7.38906
 20.0855   1.0

## Norma Matricial ## 
Para uma matriz $A \in \mathbb{R}^{m \times n}$, usamos $‖A‖$ para denotar a norma de matriz $A$, 

$$
‖A‖_{F} = \left(\sum_{i=1}^{m}\sum_{j=1}^{n}A^{2}_{ij}\right)^{\frac{1}{2}}. \quad (\mbox{Norma de Frobenius})
$$

In [141]:
A = [2 3 -1; 0 -1 4]
norm(A), norm(A[:])  # Norma de Frobenius

(5.5677643628300215, 5.5677643628300215)

In [142]:
A = [3 -1 1; 3 6 2; 3 3 7]

opnorm(A, 1),   # Norma Coluna
opnorm(A, Inf), # Norma Linha
norm(A),        # Norma Frobenius
opnorm(A, 2)   # Norma induzida p=2

(10.0, 13.0, 11.269427669584644, 10.095331331591009)

### Desigualdade Triangular 
$$‖A+B‖ ≤ ‖A‖+‖B‖$$ 

In [70]:
A = [1 -4; -5 9]; B= [3 -6; 12 0.5];
norm(A + B), norm(A) + norm(B)

(15.976545308670458, 24.847352998607022)

### Multiplicação Matriz-vetor

In [71]:
A = [20 30 -10; 15 9 5]
x = [-1, 0, 3]
A*x   # Multiplicação Matriz vetor

2-element Vector{Int64}:
 -50
   0

**Matrix de Diferencias** 
$$
\underbrace{\begin{bmatrix}
-1 & 1 & 0 & \cdots & 0 & 0 & 0 \\
 0 & -1 & 1 & \cdots & 0 & 0 & 0 \\
\vdots &  & \ddots & \ddots &  &  & \vdots \\
\vdots &  &        &\ddots  &\ddots   &  & \vdots \\
0 & 0 & 0 & \cdots & -1 & 1 & 0 \\
0 & 0 & 0 & \cdots & 0 & -1 & 1 
\end{bmatrix}}_{(n-1)\times n} 
\underbrace{\begin{bmatrix}
x_1\\
x_2\\
\vdots\\
\vdots\\
x_{n-1}\\
x_n
\end{bmatrix}}_{n\times 1}
=
\underbrace{\begin{bmatrix}
x_2 -x_1\\
x_3 -x_2\\
\vdots\\
\vdots\\
x_n - x_{n-1}
\end{bmatrix}}_{(n-1)\times 1}
$$


In [143]:
Matriz_dif(n) = [-Iden(n-1) zeros(n-1)] + [zeros(n-1) Iden(n-1)];

M = Matriz_dif(4)

3×4 Matrix{Float64}:
 -1.0   1.0   0.0  0.0
  0.0  -1.0   1.0  0.0
  0.0   0.0  -1.0  1.0

In [144]:
M*[-1,0,2,1]

3-element Vector{Float64}:
  1.0
  2.0
 -1.0

In [145]:
using SparseArrays

In [146]:
Matriz_dif(n) = [-Ide_esparsa(n-1) spzeros(n-1)] + [spzeros(n-1) Ide_esparsa(n-1)];
M = Matriz_dif(4)

3×4 SparseMatrixCSC{Float64, Int64} with 6 stored entries:
 -1.0   1.0    ⋅    ⋅ 
   ⋅   -1.0   1.0   ⋅ 
   ⋅     ⋅   -1.0  1.0

In [147]:
M*[-1,0,2,1]

3-element Vector{Float64}:
  1.0
  2.0
 -1.0

### Exemplo: 
$$
\underbrace{\begin{bmatrix}
1 & 0 & 0 & \cdots & 0 & 0  \\
1 & 1 & 0 & \cdots & 0 & 0  \\
\vdots &  & \ddots & \ddots &  & \vdots \\
\vdots &  &        &\ddots  &\ddots   & \vdots \\
1 & 1 & 1 & \cdots & 1 & 0 \\
1 & 1 & 1 & \cdots & 1 & 1 
\end{bmatrix}}_{n\times n} 
\underbrace{\begin{bmatrix}
x_1\\
x_2\\
\vdots\\
\vdots\\
x_{n-1}\\
x_n
\end{bmatrix}}_{n\times 1}
= 
\underbrace{\begin{bmatrix}
x_1\\
x_1 + x_2\\
x_1 + x_2 + x_3\\
\vdots\\
\vdots\\
x_1+ \cdots +x_n 
\end{bmatrix}}_{n\times 1}
$$


In [148]:
function Triang_unos(n) #Matriz triangular inferior n x n de 1's
    T = zeros(n,n)
    for i=1:n
        for j=1:i
            T[i,j] = 1
        end
    end
    return T
end

Triang_unos (generic function with 1 method)

In [153]:
Triang_unos(5)

5×5 Matrix{Float64}:
 1.0  0.0  0.0  0.0  0.0
 1.0  1.0  0.0  0.0  0.0
 1.0  1.0  1.0  0.0  0.0
 1.0  1.0  1.0  1.0  0.0
 1.0  1.0  1.0  1.0  1.0

In [154]:
Triang_unos(5)*[1, 2, 3, 4, 5]

5-element Vector{Float64}:
  1.0
  3.0
  6.0
 10.0
 15.0

In [186]:
import Pkg; Pkg.add("RowEchelon")

   Resolving package versions...
  No Changes to `C:\Users\kelyd\Meu Drive\_AULAS 2024.1_FELIPE\ALGEBRA LINEAR COMPUTACIONAL 2024-1\Notebooks Julia ALC\Project.toml`
  No Changes to `C:\Users\kelyd\Meu Drive\_AULAS 2024.1_FELIPE\ALGEBRA LINEAR COMPUTACIONAL 2024-1\Notebooks Julia ALC\Manifest.toml`


In [187]:
using RowEchelon

A =[1 3 8; 1 2 6; 0 1 2]
#A = [1 2 3; 0 4 5; 0 0 6] 
#A = [1 2 5; 1 2 5; 1 2 5] 
rref(A)

3×3 Matrix{Float64}:
 1.0  0.0  2.0
 0.0  1.0  2.0
 0.0  0.0  0.0